### ISSUE TITLE
Architectural Improvement: Provide Abstraction Assemblies.

### ISSUE THREAD

**Issue by viniciusmiguel** [MatterHackers/agg-sharp#1352]
I'm facing the issue of creating an application based on agg-sharp and would like to provide a public API for the application extension. The way agg is designed now, I would need to reference the library directly generating undesired dependency.

My suggestion is to extract interfaces and enumerators from Agg and Gui and create additional interfaces for classes that are not implementing their own interfaces like GuiWidget, for example, creating Agg.Abstractions and Gui.Abstractions assemblies. 

This should not generate any breaking change in code level; naturally, child projects like MatterControl need to reference the extra projects to have all the references.

I'm willing to provide a pull request with those changes if you believe the contribution will provide value to the project.

**Comment by larsbrubaker** [comment]
I think that sounds exciting. Is there a place to see the work you have in progress? We would look at anything you have done so far and certainly would review a pull request if you create one.

Always interested in the library and API evolving and having active projects using it is one of the best ways.

**Comment by viniciusmiguel** [comment]
Hello Lars, I should start soon. I'm focused on other aspects on my project right now, as soon I need to touch the UI code I will start this process in parallel.
