### ISSUE TITLE
Replace RemoveAllChildren with CloseChildren

### ISSUE THREAD

**Issue by jlewin** [MatterHackers/agg-sharp#228]
Function is frequently used as a helper method to empty a widget and we *almost certainly* want CloseChildren in all cases where we're not reusing widgets. Widgets that want the RemoveAllChildren behavior should use RemoveChild, keep their references and reuse as appropriate. This will clarify when the reuse behavior is desired and ensure we clean up resources by always calling close when no reuse was required

Rename CloseAllChildren to simply CloseChildren

As a side note jQuery thought the best way to convey this behavior was with the .Empty() function, which removes all children and releases all event references to prevent memory leaks.

**Comment by johnlewin** [comment]
As a side note jQuery long ago thought the best way to convey this behavior was with the .Empty() function, which removes all children and releases all event references to prevent memory leaks.
