### ISSUE TITLE
Android Example

### ISSUE THREAD

**Issue by alejsouza** [MatterHackers/agg-sharp#57]
Hi, can this library be used in Android? Any example?

Thanks.-
Regards.-

**Comment by larsbrubaker** [comment]
Yes it can. [MatterControl Touch](https://www.matterhackers.com/store/printer-accessories/mattercontrol-touch) is a great example. You need to use Xamarin Android to get it all working.

You can also use agg to render it memory buffers then copy those to gl.  We do lots of that.

**Comment by alejsouza** [comment]
Great! I will try to make it work with Xamarin, at least I know is possible
and you give me something to start :).

Thank you very much!

2015-10-27 17:14 GMT-03:00 Lars Brubaker <notifications@github.com>:
